### Bilan sur la répartition spatio-temporelle des surfaces brûlées 

L’étude de la caractérisation des incendies montre que 2020 est l’une des années les moins impactées par les incendies avec un total de 15 652 hectares brûlées. Cette année est considérée selon Météo France comme une année particulièrement humide étant donnée la présence prolonger du phénomène La Nina.  

L’étude de la caractérisation des incendies montre que 2020 est une de années les plus moins touchée avec un total de 15 653 hectares, soit 0,85% de la Nouvelle-Calédonie impactée par les feux. Ce constat est confirmé par une analyse temporelle, où 2020 détient près de 70% en moins d’incendies par rapport à 2019, une année très impactée, et reste comparable à 2018 avec près de 200 incendies détectés par le capteur VIIRS. Cette année est considérée selon Météo France comme une année pluvieuse suite à l’influence du phénomène la Nina. 

En s’intéressant à la saisonnalité des feux, selon les données du capteur VIIRS, il n’y a que le mois de janvier 2020 qui reste supérieur à la médiane mensuelle sur la période 2012-2020. Ce constat est également souligné par Météo France dans son bulletin climatique annuel où il y a eu un déficit pluviométrique sur le mois de janvier 2020. Sur le reste de l’année, le cumul des incendies reste faible par rapport aux médianes mensuelles 2012-2020, en correspondance avec l’analyse réalisée par Météo France, avec six épisodes pluviométriques marquants dans l’année, deux phénomènes cycloniques, avec un mois de décembre ayant un bilan pluviométrique largement excédentaire. 

Près de 88% des surfaces brûlées en 2020 concernent des secteurs jamais incendiés en comparaison avec les années précédentes entre 2017 et 2019. La répartition spatiale de ces incendies reste hétérogène sur le territoire calédonien avec une grande partie Nord de la Grande Terre plus touchée, et notamment la Province Nord qui reste la province la plus touchée avec près de 58% de la superficie impactée. La commune de Boulouparis reste la plus impactée avec près de 1 566 hectares brûlés. L’aire coutumière Hot ma whaap, constituée de trois communes les plus impactées par les incendies dépassant les 1000 hectares (Ouégoa, Kaala Gomen et Voh) concerne à elle seule près de 40% de la superficie brûlée en Nouvelle-Calédonie.  

Cette répartition correspond également aux résultats sur le substrat, où il s’agit du sol utramafique qui a été le plus impacté réparti essentiellement sur les 5 communes les plus impactées (Boulouparis, Kaala-Gomen, Ouégoa, Voh, Pouembout) avec plus de 5 000 hectares, soit près de 30% de la superficie incendiée en Nouvelle-Calédonie. 

Il est constaté que 80% des incendies se produisent à moins de 500 mètres d’une voie d’accès et ce sont près de 70% des incendies se produisent à moins d’un kilomètre d’une habitation ou d’une construction. 

En considérant la taille des zones brûlées sur l’année 2020, celles-ci sont en grande partie de petite taille, plus de 90% ne dépassant pas les 10 hectares. Avec une année assez humide, ces petites surfaces brûlées ont été plus nombreuses et participent à plus de 50% de la superficie totale brûlée. 